CREATE database LaSalDeLaTierra;

USE LaSalDeLaTierra;


CREATE TABLE TERRENOS (

ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
NOMBRE VARCHAR(20) NOT NULL UNIQUE,
DESCRIPCION VARCHAR(500) NOT NULL

);


CREATE TABLE EDIFICACIONES (

ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
NOMBRE VARCHAR(20) NOT NULL UNIQUE,
DESCRIPCION VARCHAR(500) NOT NULL,
EFECTO TINYINT NOT NULL

);


CREATE TABLE COSTOS_EDIFICACIONES (

ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
ID_EDIFICACION INT NOT NULL,
INDUSTRIA TINYINT NOT NULL,
RIQUEZA TINYINT NOT NULL,
RIQ_X_TURNO BOOLEAN NOT NULL,
FOREIGN KEY (ID_EDIFICACION) REFERENCES EDIFICACIONES(ID)

);


CREATE TABLE CULTIVOS (

ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
NOMBRE VARCHAR(20) NOT NULL UNIQUE,
ESTACION TINYINT(2) NOT NULL	# 0 Primavera, 1 Verano, 2 Otoño.

);


CREATE TABLE ARBOLES (

ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
NOMBRE VARCHAR(20) NOT NULL UNIQUE

);


CREATE TABLE ANIMALES (

ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
NOMBRE VARCHAR(20) NOT NULL,
DOMESTICO BOOLEAN NOT NULL	# 0 Salvaje, 1 Domestico.

);


CREATE TABLE YACIMIENTOS (

ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
NOMBRE VARCHAR(20) NOT NULL UNIQUE,
TIPO TINYINT(2) NOT NULL	# 0 Piedra, 1 Gema, 2 Metal.

);



CREATE TABLE ACCIONES_DE_CIUDAD (

ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
NOMBRE VARCHAR(40) NOT NULL UNIQUE,
REQUISITO VARCHAR(500) NOT NULL,
DESCRIPCION VARCHAR(500) NOT NULL,
EFECTO TINYINT NOT NULL

);


CREATE TABLE COSTOS_ACCIONES_DE_CIUDAD (

ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
ID_ACCION INT NOT NULL,
INDUSTRIA TINYINT NOT NULL,
POBLACION TINYINT NOT NULL,
RIQUEZA TINYINT NOT NULL,
FOREIGN KEY (ID_ACCION) REFERENCES ACCIONES_DE_CIUDAD(ID)

);


CREATE TABLE MILITARES (

ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
TIPO BOOLEAN NOT NULL,	# 0 Militar, 1 Elite
FUERZA INT NOT NULL,
BONO_IMPACTO INT NOT NULL,
DEFENSA INT NOT NULL,
VELOCIDAD INT NOT NULL,
SUELDO INT NOT NULL

);


CREATE TABLE ELITES (

ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
ID_MILITAR INT NOT NULL,
ESPECIAL VARCHAR(300) NOT NULL,
FOREIGN KEY (ID_MILITAR) REFERENCES MILITARES(ID)

);


CREATE TABLE ACCIONES_DE_UNIDAD (

ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
NOMBRE VARCHAR(20) NOT NULL UNIQUE,
TIPO TINYINT(2) NOT NULL,	# 0 Militar, 1 Caravana, 2 Explorador.
DESCRIPCION VARCHAR(500) NOT NULL

);


CREATE TABLE COSTOS_ACCIONES_DE_UNIDAD (

ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
ID_ACCION INT NOT NULL,
INDUSTRIA TINYINT NOT NULL,
POBLACION TINYINT NOT NULL,
RIQUEZA TINYINT NOT NULL,
FOREIGN KEY (ID_ACCION) REFERENCES ACCIONES_DE_UNIDAD(ID)

);


CREATE TABLE MODIFICADORES_DE_ATAQUE (

ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
NOMBRE VARCHAR(20) NOT NULL,
MODIFICADOR TINYINT, # Puede ser null por la modificacion "asset" que da un modificador variable
DESCRIPCION VARCHAR(500)

);

