# STORED PROCEDURES

DELIMITER $$
CREATE PROCEDURE EDIFICACIONES_CON_COSTO()

BEGIN

SELECT E.ID, E.NOMBRE, E.DESCRIPCION, E.EFECTO, C.INDUSTRIA, C.RIQUEZA, C.RIQ_X_TURNO FROM EDIFICACIONES AS E
INNER JOIN COSTOS_EDIFICACIONES AS C ON E.ID = C.ID_EDIFICACION
ORDER BY E.NOMBRE ASC;

END $$
DELIMITER ;


DELIMITER $$
CREATE PROCEDURE EDIFICACIONES_INDUSTRIA()

BEGIN

SELECT E.ID, E.NOMBRE, E.DESCRIPCION, E.EFECTO, C.INDUSTRIA, C.RIQUEZA, C.RIQ_X_TURNO FROM EDIFICACIONES AS E
INNER JOIN COSTOS_EDIFICACIONES AS C ON E.ID = C.ID_EDIFICACION
WHERE C.INDUSTRIA > 0
ORDER BY E.NOMBRE ASC;

END $$
DELIMITER ;


DELIMITER $$
CREATE PROCEDURE EDIFICACIONES_RIQUEZA()

BEGIN

SELECT E.ID, E.NOMBRE, E.DESCRIPCION, E.EFECTO, C.INDUSTRIA, C.RIQUEZA, C.RIQ_X_TURNO FROM EDIFICACIONES AS E
INNER JOIN COSTOS_EDIFICACIONES AS C ON E.ID = C.ID_EDIFICACION
WHERE C.RIQUEZA > 0
ORDER BY E.NOMBRE ASC;

END $$
DELIMITER ;


DELIMITER $$
CREATE PROCEDURE MODIFICAR_EDIFICACION(ID_FILTRO INT, NOMBRE_NUEVO VARCHAR(20), DESCRIPCION_NUEVA VARCHAR(500), EFECTO_NUEVO TINYINT, INDUSTRIA_NUEVA TINYINT, RIQUEZA_NUEVA TINYINT, RIQ_X_TURNO_NUEVA BOOLEAN) 

BEGIN

START TRANSACTION;

UPDATE EDIFICACIONES
SET
NOMBRE = NOMBRE_NUEVO,
DESCRIPCION = DESCRIPCION_NUEVA,
EFECTO = EFECTO_NUEVO
WHERE ID = ID_FILTRO;

UPDATE COSTOS_EDIFICACIONES
SET
INDUSTRIA = INDUSTRIA_NUEVA,
RIQUEZA = RIQUEZA_NUEVA,
RIQ_X_TURNO = RIQ_X_TURNO_NUEVA
WHERE ID_EDIFICACION = ID_FILTRO;

COMMIT;

END $$
DELIMITER ;


DELIMITER $$
CREATE PROCEDURE EDIFICACION_X_NOMBRE(NOMBRE_FILTRO VARCHAR(20))

BEGIN

SELECT E.ID, E.NOMBRE, E.DESCRIPCION, E.EFECTO, C.INDUSTRIA, C.RIQUEZA, C.RIQ_X_TURNO FROM EDIFICACIONES AS E
INNER JOIN COSTOS_EDIFICACIONES AS C ON E.ID = C.ID_EDIFICACION
WHERE E.NOMBRE = NOMBRE_FILTRO;

END $$
DELIMITER ;