# STORED PROCEDURES

DELIMITER $$
CREATE PROCEDURE EDIFICACIONES_CON_COSTO()

BEGIN

	SELECT E.ID, E.NOMBRE, E.DESCRIPCION, E.EFECTO, C.INDUSTRIA, C.RIQUEZA, C.RIQ_X_TURNO FROM EDIFICACIONES AS E
	INNER JOIN COSTOS_EDIFICACIONES AS C ON E.ID = C.ID_EDIFICACION
	ORDER BY E.NOMBRE ASC;

END $$
DELIMITER ;


DELIMITER $$
CREATE PROCEDURE EDIFICACIONES_INDUSTRIA()

BEGIN

	SELECT E.ID, E.NOMBRE, E.DESCRIPCION, E.EFECTO, C.INDUSTRIA, C.RIQUEZA, C.RIQ_X_TURNO FROM EDIFICACIONES AS E
	INNER JOIN COSTOS_EDIFICACIONES AS C ON E.ID = C.ID_EDIFICACION
	WHERE C.INDUSTRIA > 0
	ORDER BY E.NOMBRE ASC;

END $$
DELIMITER ;


DELIMITER $$
CREATE PROCEDURE EDIFICACIONES_RIQUEZA()

BEGIN

	SELECT E.ID, E.NOMBRE, E.DESCRIPCION, E.EFECTO, C.INDUSTRIA, C.RIQUEZA, C.RIQ_X_TURNO FROM EDIFICACIONES AS E
	INNER JOIN COSTOS_EDIFICACIONES AS C ON E.ID = C.ID_EDIFICACION
	WHERE C.RIQUEZA > 0
	ORDER BY E.NOMBRE ASC;

END $$
DELIMITER ;


DELIMITER $$
CREATE PROCEDURE MODIFICAR_EDIFICACION(ID_FILTRO INT, NOMBRE_NUEVO VARCHAR(20), DESCRIPCION_NUEVA VARCHAR(500), EFECTO_NUEVO TINYINT, INDUSTRIA_NUEVA TINYINT, RIQUEZA_NUEVA TINYINT, RIQ_X_TURNO_NUEVA BOOLEAN) 

BEGIN

	START TRANSACTION;

		UPDATE EDIFICACIONES
		SET
		NOMBRE = NOMBRE_NUEVO,
		DESCRIPCION = DESCRIPCION_NUEVA,
		EFECTO = EFECTO_NUEVO
		WHERE ID = ID_FILTRO;

		UPDATE COSTOS_EDIFICACIONES
		SET
		INDUSTRIA = INDUSTRIA_NUEVA,
		RIQUEZA = RIQUEZA_NUEVA,
		RIQ_X_TURNO = RIQ_X_TURNO_NUEVA
		WHERE ID_EDIFICACION = ID_FILTRO;

	COMMIT;

END $$
DELIMITER ;


DELIMITER $$
CREATE PROCEDURE EDIFICACION_X_NOMBRE(NOMBRE_FILTRO VARCHAR(20))

BEGIN

	SELECT E.ID, E.NOMBRE, E.DESCRIPCION, E.EFECTO, C.INDUSTRIA, C.RIQUEZA, C.RIQ_X_TURNO FROM EDIFICACIONES AS E
	INNER JOIN COSTOS_EDIFICACIONES AS C ON E.ID = C.ID_EDIFICACION
	WHERE E.NOMBRE = NOMBRE_FILTRO;

END $$
DELIMITER ;


DELIMITER $$
CREATE PROCEDURE AGREGAR_EDIFICACION(
    NOMBRE_EDIF VARCHAR(20),
    DESCRIPCION_EDIF VARCHAR(500), 
    EFECTO_EDIF TINYINT, 
    INDUSTRIA_EDIF TINYINT, 
    RIQUEZA_EDIF TINYINT, 
    RIQ_X_TURNO_EDIF BOOLEAN)

BEGIN

	DECLARE ULTIMO_ID INT;
    DECLARE RESULTADO TINYINT;
    SET RESULTADO = 0;

	START TRANSACTION;

		IF NOT EXISTS (SELECT 1 FROM EDIFICACIONES E WHERE E.NOMBRE = NOMBRE_EDIF) 
		THEN

			INSERT INTO EDIFICACIONES (NOMBRE, DESCRIPCION, EFECTO)
			VALUES(NOMBRE_EDIF, DESCRIPCION_EDIF, EFECTO_EDIF);

			SET ULTIMO_ID = LAST_INSERT_ID();

			INSERT INTO COSTOS_EDIFICACIONES (ID_EDIFICACION, INDUSTRIA, RIQUEZA, RIQ_X_TURNO)
			VALUES(ULTIMO_ID, INDUSTRIA_EDIF, RIQUEZA_EDIF, RIQ_X_TURNO_EDIF);

			SET RESULTADO = 1;

		END IF;

		SELECT RESULTADO AS RESULTADO;

	COMMIT;

END $$
DELIMITER ;


DELIMITER $$
CREATE PROCEDURE ELIMINAR_EDIFICACION(NOMBRE_EDIFICACION VARCHAR(20))

BEGIN

    DECLARE FILAS_AFECTADAS INT DEFAULT 0;
    DECLARE ID_EDIFICACION_ELIMINADA INT;

	START TRANSACTION;

		SELECT ID INTO ID_EDIFICACION_ELIMINADA FROM EDIFICACIONES WHERE NOMBRE = NOMBRE_EDIFICACION;
        
        IF ID_EDIFICACION_ELIMINADA IS NOT NULL THEN
        
			DELETE FROM COSTOS_EDIFICACIONES WHERE ID_EDIFICACION = ID_EDIFICACION_ELIMINADA;
			DELETE FROM EDIFICACIONES WHERE ID = ID_EDIFICACION_ELIMINADA;
			
			SET FILAS_AFECTADAS = ROW_COUNT(); #Si borro algo, no deberia ser 0.

		END IF;
        
	COMMIT;
    
    SELECT FILAS_AFECTADAS > 0 AS RESULTADO;

END $$
DELIMITER ;


DELIMITER $$
CREATE PROCEDURE MODIFICAR_TERRENO(ID_FILTRO INT, NOMBRE_NUEVO VARCHAR(20), DESCRIPCION_NUEVA VARCHAR(500)) 

BEGIN

	UPDATE TERRENOS
	SET
	NOMBRE = NOMBRE_NUEVO,
	DESCRIPCION = DESCRIPCION_NUEVA
	WHERE ID = ID_FILTRO;

END $$
DELIMITER ;


DELIMITER $$

CREATE PROCEDURE ELIMINAR_TERRENO(NOMBRE_TERRENO VARCHAR(20))

BEGIN

    DELETE FROM TERRENOS WHERE NOMBRE = NOMBRE_TERRENO;

    SELECT ROW_COUNT() > 0 AS RESULTADO;
    
END $$

DELIMITER ;


DELIMITER $$
CREATE PROCEDURE AGREGAR_TERRENO(
    NOMBRE_TERR VARCHAR(20),
    DESCRIPCION_TERR VARCHAR(500)
    )

BEGIN

    DECLARE RESULTADO TINYINT;
    SET RESULTADO = 0;

		IF NOT EXISTS (SELECT 1 FROM TERRENOS T WHERE T.NOMBRE = NOMBRE_TERR) 
		THEN

			INSERT INTO TERRENOS (NOMBRE, DESCRIPCION)
			VALUES(NOMBRE_TERR, DESCRIPCION_TERR);

			SET RESULTADO = 1;

		END IF;

		SELECT RESULTADO AS RESULTADO;

END $$
DELIMITER ;


DELIMITER $$
CREATE PROCEDURE ACCIONES_DE_CIUDAD_CON_COSTO()

BEGIN

	SELECT A.ID, A.NOMBRE, A.REQUISITO, A.DESCRIPCION, A.EFECTO, C.INDUSTRIA, C.POBLACION, C.RIQUEZA FROM ACCIONES_DE_CIUDAD AS A
	INNER JOIN COSTOS_ACCIONES_DE_CIUDAD AS C ON A.ID = C.ID_ACCION
	ORDER BY A.NOMBRE ASC;

END $$
DELIMITER ;


DELIMITER $$
CREATE PROCEDURE MODIFICAR_ACCION_DE_CIUDAD(

	ID_FILTRO INT, NOMBRE_NUEVO VARCHAR(40),
    REQUISITO_NUEVO VARCHAR(500),
    DESCRIPCION_NUEVA VARCHAR(500),
    EFECTO_NUEVO TINYINT,
    INDUSTRIA_NUEVA TINYINT,
    POBLACION_NUEVA TINYINT,
    RIQUEZA_NUEVA TINYINT
    
    ) 

BEGIN

	START TRANSACTION;

		UPDATE ACCIONES_DE_CIUDAD
		SET
		NOMBRE = NOMBRE_NUEVO,
        REQUISITO = REQUISITO_NUEVO,
		DESCRIPCION = DESCRIPCION_NUEVA,
		EFECTO = EFECTO_NUEVO
		WHERE ID = ID_FILTRO;

		UPDATE COSTOS_ACCIONES_DE_CIUDAD
		SET
		INDUSTRIA = INDUSTRIA_NUEVA,
        POBLACION = POBLACION_NUEVA,
		RIQUEZA = RIQUEZA_NUEVA
		WHERE ID_ACCION = ID_FILTRO;

	COMMIT;

END $$
DELIMITER ;


DELIMITER $$
CREATE PROCEDURE ACCION_DE_CIUDAD_X_NOMBRE(NOMBRE_FILTRO VARCHAR(40))

BEGIN

	SELECT A.ID, A.NOMBRE, A.REQUISITO, A.DESCRIPCION, A.EFECTO, C.INDUSTRIA, C.POBLACION, C.RIQUEZA FROM ACCIONES_DE_CIUDAD AS A
	INNER JOIN COSTOS_ACCIONES_DE_CIUDAD AS C ON A.ID = C.ID_ACCION
	WHERE A.NOMBRE = NOMBRE_FILTRO;

END $$
DELIMITER ;